# Real world Scenario with Numpy

<hr>

<img src="https://i.imgur.com/mRN9H4v.png"/>

In [32]:
import numpy as np

In [33]:
names = np.array(("Khaled", "Sarah", "Mohammed", "Reem","Fahad", "Saleh", "Nora"))
ages = np.array((17, 60, 21, 55, 29, 24, 19))

In [34]:
# write your code here ^_^
sorted_indices = np.argsort(-ages)

sorted_names = names[sorted_indices]

for i, name in enumerate(sorted_names):
    print(f"{i+1}- {name}")

1- Sarah
2- Reem
3- Fahad
4- Saleh
5- Mohammed
6- Nora
7- Khaled


<hr>

<img src="https://i.imgur.com/jbHKBPR.png![image.png](attachment:49d72e8d-c091-43ab-8ecd-db9a79858664.png)![image.png](attachment:ae9cf8e0-d2c1-4396-8bfc-0d7016cff2ad.png)![image.png](attachment:8f96c12e-5e2a-432b-b706-429bbafdeccc.png)![image.png](attachment:bd54d228-298e-4fdd-8464-49002837e5e5.png)"/>

In [35]:
import calendar
import numpy as np


In [36]:
month_names = list(calendar.month_name)[1:]
temperature_data = np.array([40, 38, 28, 20, 15, 28, 35, 40, 48, 45, 40, 43])
threshold = 35

In [37]:
# write your code here ^_^
# Calculate the average temperature for the year.
average_temperature = np.mean(temperature_data)
print("The average temperature for the year:", average_temperature)

#Find the months with temperatures above the threshold.
above_threshold_months = np.where(temperature_data > threshold)[0]
above_threshold_month_names = [month_names[i] for i in above_threshold_months]
print("The months with temperatures above the threshold:", above_threshold_month_names)

#Determine the month with the highest and lowest temperature
highest_temperature_month_index = np.argmax(temperature_data)
lowest_temperature_month_index = np.argmin(temperature_data)
highest_temperature_month = month_names[highest_temperature_month_index]
lowest_temperature_month = month_names[lowest_temperature_month_index]
print("The month with the highest temperature:", highest_temperature_month)
print("The month with the lowest temperature:", lowest_temperature_month)

#Calculate the temperature range
temperature_range = np.max(temperature_data) - np.min(temperature_data)
print("Temperature range:", temperature_range)


The average temperature for the year: 35.0
The months with temperatures above the threshold: ['January', 'February', 'August', 'September', 'October', 'November', 'December']
The month with the highest temperature: September
The month with the lowest temperature: May
Temperature range: 33


<hr>

<img src="https://i.imgur.com/eiXHG9y.png"/>

In [38]:
students = np.array(['Mohammed', 'Lama', 'Norah', 'Ahmed', 'Fahad'])
math_scores = np.array([80, 92, 75, 68, 88])
ML_scores = np.array([85, 78, 92, 64, 90])
DS_scores = np.array([70, 88, 75, 82, 78])

In [39]:
# write your code here ^_^
#Calculating statistics for each subject
# Math scores statistics
math_avg = np.mean(math_scores)
math_max = np.max(math_scores)
math_min = np.min(math_scores)
math_std = np.std(math_scores)

print("Math Scores Statistics:")
print("Average score:", math_avg)
print("Highest score:", math_max)
print("Lowest score:", math_min)
print("Standard deviation of scores:", math_std)
print()
print("---------------------------")

# Data Structure scores statistics
DS_avg = np.mean(DS_scores)
DS_max = np.max(DS_scores)
DS_min = np.min(DS_scores)
DS_std = np.std(DS_scores)

print("Data Structure Scores Statistics:")
print("Average score:", DS_avg)
print("Highest score:", DS_max)
print("Lowest score:", DS_min)
print("Standard deviation of scores:", DS_std)
print()

print("---------------------------")
# Machine Learning scores statistics
ML_avg = np.mean(ML_scores)
ML_max = np.max(ML_scores)
ML_min = np.min(ML_scores)
ML_std = np.std(ML_scores)

print("Machine Learning Scores Statistics:")
print("Average score:", ML_avg)
print("Highest score:", ML_max)
print("Lowest score:", ML_min)
print("Standard deviation of scores:", ML_std)
print()


Math Scores Statistics:
Average score: 80.6
Highest score: 92
Lowest score: 68
Standard deviation of scores: 8.662563131083086

---------------------------
Data Structure Scores Statistics:
Average score: 78.6
Highest score: 88
Lowest score: 70
Standard deviation of scores: 6.118823416311342

---------------------------
Machine Learning Scores Statistics:
Average score: 81.8
Highest score: 92
Lowest score: 64
Standard deviation of scores: 10.127191120937729



In [40]:
#Finding the student with the highest and lowest overall average scores:
# Calculate overall average scores
overall_avg_scores = (math_scores + DS_scores + ML_scores) / 3

# Find the student with the highest overall average score
highest_avg_student = students[np.argmax(overall_avg_scores)]

# Find the student with the lowest overall average score
lowest_avg_student = students[np.argmin(overall_avg_scores)]

print("Student with the highest overall average score:", highest_avg_student)
print("Student with the lowest overall average score:", lowest_avg_student)
print()

Student with the highest overall average score: Lama
Student with the lowest overall average score: Ahmed



In [50]:
#Identifying students who failed (average score below 40) in any subject:
# Check if any student has an average score below 40 in any subject
failed_students = []

for i in range(len(students)):
    if math_scores[i] < 40 or DS_scores[i] < 40 or ML_scores[i] < 40:
        failed_students.append(students[i])

if len(failed_students) > 0:
    print("Students who failed in any subject:")
    for student in failed_students:
        print(student)
else:
    print("No students failed in any subject.")

No students failed in any subject.


In [42]:
#Normalizing the scores to have a mean of 0 and a standard deviation of 1 in each subject:
# Normalize the scores using z-score normalization
normalized_math_scores = (math_scores - np.mean(math_scores)) / np.std(math_scores)
normalized_DS_scores = (DS_scores - np.mean(DS_scores)) / np.std(DS_scores)
normalized_ML_scores = (ML_scores - np.mean(ML_scores)) / np.std(ML_scores)

print("Normalized Math Scores:")
print(normalized_math_scores)
print()

print("Normalized Data Structure Scores:")
print(normalized_DS_scores)
print()

print("Normalized Machine Learning Scores:")
print(normalized_ML_scores)

Normalized Math Scores:
[-0.06926356  1.31600773 -0.64645994 -1.45453485  0.85425063]

Normalized Data Structure Scores:
[-1.40549897  1.53624306 -0.58834841  0.55566238 -0.09805807]

Normalized Machine Learning Scores:
[ 0.315981   -0.37522744  1.00718944 -1.75764432  0.80970132]


<hr>

### <center> Great job! Keep exploring and learning. Your progress is remarkable.

<hr>

<hr>